blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for Tuya
    url: https://discord.gg/8fpZA4S
    about: Please ask and answer questions here.
  - name: Homebridge-tuya-camera - Pull Requests
    url: https://github.com/donavanbecker/homebridge-tuya-camera/pulls
    about: Please report security vulnerabilities here.
